# Generated by Django 5.1.6 on 2025-03-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activities",
            fields=[
                (
                    "activity_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("sport", models.CharField(blank=True, max_length=255, null=True)),
                ("sub_sport", models.CharField(blank=True, max_length=255, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("stop_time", models.DateTimeField(blank=True, null=True)),
                ("elapsed_time", models.FloatField(blank=True, null=True)),
                ("moving_time", models.FloatField(blank=True, null=True)),
                ("distance", models.FloatField(blank=True, null=True)),
                ("avg_speed", models.FloatField(blank=True, null=True)),
                ("max_speed", models.FloatField(blank=True, null=True)),
                ("avg_hr", models.FloatField(blank=True, null=True)),
                ("max_hr", models.FloatField(blank=True, null=True)),
                ("calories", models.FloatField(blank=True, null=True)),
                ("avg_cadence", models.FloatField(blank=True, null=True)),
                ("max_cadence", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "activities",
                "managed": False,
            },
        ),
    ]
