# Generated by Django 5.1.6 on 2025-03-15 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="activities",
            table="garmin_activities",
        ),
    ]
