# Generated by Django 5.1.6 on 2025-03-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_alter_activities_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="activities",
            table="activities",
        ),
    ]
