# Generated by Django 5.1.6 on 2025-03-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RestingHR",
            fields=[
                ("day", models.DateField(primary_key=True, serialize=False)),
                ("resting_heart_rate", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "resting_hr",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sleep",
            fields=[
                ("day", models.DateField(primary_key=True, serialize=False)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("total_sleep", models.TimeField()),
                ("deep_sleep", models.TimeField()),
                ("light_sleep", models.TimeField()),
                ("rem_sleep", models.TimeField()),
                ("awake", models.TimeField()),
                ("avg_spo2", models.FloatField(blank=True, null=True)),
                ("avg_rr", models.FloatField(blank=True, null=True)),
                ("avg_stress", models.FloatField(blank=True, null=True)),
                ("score", models.IntegerField(blank=True, null=True)),
                ("qualifier", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "sleep",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SleepEvent",
            fields=[
                ("timestamp", models.DateTimeField(primary_key=True, serialize=False)),
                ("event", models.CharField(blank=True, max_length=100, null=True)),
                ("duration", models.TimeField()),
            ],
            options={
                "db_table": "sleep_events",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Stress",
            fields=[
                ("timestamp", models.DateTimeField(primary_key=True, serialize=False)),
                ("stress", models.IntegerField()),
            ],
            options={
                "db_table": "stress",
                "managed": False,
            },
        ),
    ]
